const MAPPING_PROVINCIAS = {
    "Azuay": { pueblo: "Kichwa Kañari", asentamientos: "Pumamungo, Gualaceo, Chordeleg" },
    "Bolívar": { pueblo: "Kichwa Waranka", asentamientos: "Guaranda, Chimbo, San Miguel" },
    "Cañar": { pueblo: "Kichwa Kañari", asentamientos: "Ingapirca, Cojitambo, Azogues" },
    "Carchi": { pueblo: "Pueblo Pasto", asentamientos: "Tulcán, San Gabriel, El Ángel" },
    "Chimborazo": { pueblo: "Kichwa Puruhá", asentamientos: "Riobamba, Colta, Guamote" },
    "Cotopaxi": { pueblo: "Kichwa Panzaleo", asentamientos: "Latacunga, Pujilí, Saquisilí" },
    "El Oro": { pueblo: "Montubio", asentamientos: "Machala, Zaruma, El Guabo" },
    "Esmeraldas": { pueblo: "Afroecuatoriano", asentamientos: "Esmeraldas, Atacames, Muisne" },
    "Galápagos": { pueblo: "Galapagueño", asentamientos: "Puerto Ayora, Puerto Baquerizo" },
    "Guayas": { pueblo: "Montubio", asentamientos: "Guayaquil, Daule, Samborondón" },
    "Imbabura": { pueblo: "Kichwa Otavalo", asentamientos: "Otavalo, Cotacachi, Ibarra" },
    "Loja": { pueblo: "Kichwa Saraguro", asentamientos: "Saraguro, Loja, Vilcabamba" },
    "Los Ríos": { pueblo: "Montubio", asentamientos: "Quevedo, Babahoyo, Vinces" },
    "Manabí": { pueblo: "Montubio", asentamientos: "Manta, Portoviejo, Montecristi" },
    "Morona Santiago": { pueblo: "Shuar", asentamientos: "Macas, Sucúa, Gualaquiza" },
    "Napo": { pueblo: "Kichwa Amazónico", asentamientos: "Tena, Archidona, Ahuano" },
    "Orellana": { pueblo: "Waorani", asentamientos: "Coca, Loreto, Aguarico" },
    "Pastaza": { pueblo: "Achuar", asentamientos: "Puyo, Mera, Shell" },
    "Pichincha": { pueblo: "Kichwa Kitu Kara", asentamientos: "Quito, Machachi, Sangolquí" },
    "Santa Elena": { pueblo: "Pueblo Huancavilca", asentamientos: "Santa Elena, Salinas, Olón" },
    "Santo Domingo de los Tsáchilas": { pueblo: "Tsáchila", asentamientos: "Chigüilpe, Congoma, El Poste" },
    "Sucumbíos": { pueblo: "Siona-Secoya", asentamientos: "Lago Agrio, Shushufindi" },
    "Tungurahua": { pueblo: "Kichwa Salasaka", asentamientos: "Ambato, Salasaka, Baños" },
    "Zamora Chinchipe": { pueblo: "Shuar", asentamientos: "Zamora, Yantzaza, Chinchipe" }
};
